services:
  nginx:
    image: nginx:1.29.1-alpine
    ports:
      - "${HTTP_PORT:-80}:8100"
    volumes:
      - ./docker/nginx/conf.d/dev.conf:/etc/nginx/conf.d/dev.conf:ro
      - ./public:/usr/src/app/public

  web-app:
    build:
      dockerfile: Dockerfile
      target: web-app
      context: .
    volumes:
      - .:/usr/src/app:ro
      - ./docker/uwsgi:/usr/local/etc/uwsgi:ro
